# Generated by Django 2.0.4 on 2018-06-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestColorA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='제품버전')),
                ('case', models.FileField(upload_to='testcolor/testcolora/', verbose_name='테스트결과')),
            ],
        ),
        migrations.CreateModel(
            name='TestColorS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='제품버전')),
                ('case', models.FileField(upload_to='testcolor/testcolors/', verbose_name='테스트결과')),
            ],
        ),
    ]
