# Generated by Django 3.0.5 on 2020-04-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='이름')),
                ('program', models.FileField(upload_to='programs/', verbose_name='프로그램')),
            ],
        ),
        migrations.CreateModel(
            name='TestColorA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='제품버전')),
                ('case', models.FileField(upload_to='testcolor/testcolora/', verbose_name='테스트결과')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='등록')),
            ],
            options={
                'verbose_name_plural': 'TestColorA',
            },
        ),
        migrations.CreateModel(
            name='TestColorS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='제품버전')),
                ('case', models.FileField(upload_to='testcolor/testcolors/', verbose_name='테스트결과')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='등록')),
            ],
            options={
                'verbose_name_plural': 'TestColorS',
            },
        ),
    ]
