# Generated by Django 2.0.4 on 2018-06-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityauto', '0002_auto_20180614_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcolora',
            options={'verbose_name_plural': 'TestColorA'},
        ),
        migrations.AlterField(
            model_name='testcolora',
            name='version',
            field=models.CharField(max_length=20, unique=True, verbose_name='제품버전'),
        ),
        migrations.AlterField(
            model_name='testcolors',
            name='version',
            field=models.CharField(max_length=20, unique=True, verbose_name='제품버전'),
        ),
    ]
