# Generated by Django 2.0.4 on 2018-06-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionauto', '0011_auto_20180612_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotest',
            name='path',
            field=models.CharField(blank=True, choices=[('/home/qceo/windowshare/Linux', 'Linux'), ('/home/qceo/windowshare/Solaris_intel', 'Solaris'), ('/home/qceo/windowshare/UNIX', 'UNIX')], max_length=100, verbose_name='경로'),
        ),
    ]
