# Generated by Django 2.0.4 on 2018-04-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20180419_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='impossble',
            new_name='impossible',
        ),
    ]
