# Generated by Django 2.0.4 on 2018-04-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20180419_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='list',
            field=models.TextField(blank=True, verbose_name='결함목록'),
        ),
        migrations.AlterField(
            model_name='bestdefact',
            name='case',
            field=models.FileField(blank=True, upload_to='case/', verbose_name='케이스 생성'),
        ),
    ]
