# Generated by Django 2.0.2 on 2018-03-23 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('project', models.CharField(blank=True, max_length=30, verbose_name='프로젝트')),
                ('role', models.CharField(blank=True, choices=[('PG', '개발자'), ('MG', '관리자'), ('EC', '기타')], max_length=2, verbose_name='역할')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='번호')),
                ('project', models.CharField(max_length=30, verbose_name='프로젝트')),
                ('type', models.CharField(max_length=10, verbose_name='유형')),
                ('state', models.CharField(max_length=15, verbose_name='상태')),
                ('realize', models.CharField(blank=True, max_length=4, verbose_name='구현')),
                ('priority', models.CharField(max_length=8, verbose_name='우선순위')),
                ('subject', models.TextField(verbose_name='제목')),
                ('author', models.TextField(max_length=6, verbose_name='저자')),
                ('charge', models.TextField(max_length=6, verbose_name='담당자')),
                ('category', models.TextField(blank=True, max_length=8, verbose_name='범주')),
                ('targetversion', models.TextField(blank=True, max_length=20, verbose_name='목표버전')),
                ('change', models.DateTimeField(blank=True, null=True, verbose_name='변경')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='시작시간')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='완료기한')),
                ('client', models.TextField(blank=True, max_length=20, verbose_name='고객사')),
                ('degree', models.TextField(blank=True, max_length=10, verbose_name='결함등급')),
                ('inputdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=30, verbose_name='프로젝트')),
                ('version', models.CharField(max_length=30, verbose_name='버전')),
                ('start', models.DateField(verbose_name='시작점')),
                ('firststep', models.DateField(verbose_name='중간단계1')),
                ('secondstep', models.DateField(verbose_name='중간단계2')),
                ('thirdstep', models.DateField(verbose_name='중간단계3')),
                ('end', models.DateField(verbose_name='종료점')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='보고서')),
                ('is_deleted', models.BooleanField(default=True, verbose_name='등록')),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
    ]
