# Generated by Django 2.0 on 2018-03-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalquality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manualtest', models.IntegerField(verbose_name='수동테스트')),
                ('process', models.IntegerField(verbose_name='프로세스')),
                ('faulty', models.IntegerField(verbose_name='결함도')),
                ('date', models.DateField(verbose_name='날짜')),
            ],
        ),
    ]
