# Generated by Django 2.0.4 on 2018-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproc', '0004_productquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end',
            field=models.DateField(verbose_name='설치마감일(프로세스마감일)'),
        ),
        migrations.AlterField(
            model_name='process',
            name='firststep',
            field=models.DateField(verbose_name='개발마감일'),
        ),
        migrations.AlterField(
            model_name='process',
            name='secondstep',
            field=models.DateField(verbose_name='품질점검마감일'),
        ),
        migrations.AlterField(
            model_name='process',
            name='start',
            field=models.DateField(verbose_name='프로세스시작일'),
        ),
        migrations.AlterField(
            model_name='process',
            name='thirdstep',
            field=models.DateField(verbose_name='패키징마감일'),
        ),
    ]
