# Generated by Django 2.0.4 on 2018-06-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproc', '0005_auto_20180417_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquality',
            name='product',
            field=models.CharField(choices=[('SecuMS', 'SecuMS'), ('Omni Guard Unix', 'Omni Guard Unix'), ('Omni Guard Windows', 'Omni Guard Windows'), ('FOSS Guard', 'FOSS Guard'), ('Athene', 'Athene')], max_length=30, verbose_name='프로젝트'),
        ),
    ]
