# Generated by Django 2.0.4 on 2018-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproc', '0006_auto_20180605_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquality',
            name='product',
            field=models.CharField(choices=[('SecuMS', 'SecuMS'), ('OmniGuard Unix', 'OmniGuard Unix'), ('OmniGuard Windows', 'OmniGuard Windows'), ('FOSSGuard', 'FOSSGuard'), ('Athena', 'Athena')], max_length=30, verbose_name='프로젝트'),
        ),
    ]
