# Generated by Django 2.0.4 on 2018-05-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0008_auto_20180509_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='p1cpu',
            field=models.CharField(blank=True, max_length=30, verbose_name='p1CPU사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p1memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='p1메모리사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p2cpu',
            field=models.CharField(blank=True, max_length=30, verbose_name='p2CPU사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p2memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='p2메모리사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p3cpu',
            field=models.CharField(blank=True, max_length=30, verbose_name='p3CPU사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p3memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='p3메모리사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p4cpu',
            field=models.CharField(blank=True, max_length=30, verbose_name='p4CPU사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p4memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='p4메모리사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p5cpu',
            field=models.CharField(blank=True, max_length=30, verbose_name='p5CPU사용량'),
        ),
        migrations.AddField(
            model_name='performance',
            name='p5memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='p5메모리사용량'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='cpu',
            field=models.CharField(blank=True, max_length=30, verbose_name='전체CPU사용량'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='전체메모리사용량'),
        ),
    ]
