# Generated by Django 2.0.4 on 2018-05-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0009_auto_20180510_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='performagent',
            name='process5',
            field=models.CharField(blank=True, max_length=20, verbose_name='프로세스5'),
        ),
    ]
