# Generated by Django 2.0.4 on 2018-05-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0012_remove_performagent_ostype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performagent',
            name='agentpath',
        ),
        migrations.RemoveField(
            model_name='performagent',
            name='name',
        ),
        migrations.AddField(
            model_name='performagent',
            name='ostype',
            field=models.CharField(blank=True, max_length=10, verbose_name='OS'),
        ),
    ]
