# Generated by Django 2.0.4 on 2018-05-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='제품명')),
                ('version', models.CharField(max_length=30, verbose_name='버전')),
                ('logpath', models.CharField(max_length=50, verbose_name='로그경로')),
            ],
        ),
        migrations.CreateModel(
            name='Loglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='제품명')),
                ('version', models.CharField(max_length=30, verbose_name='버전')),
                ('whitelist', models.TextField(blank=True, verbose_name='허용문구')),
                ('blacklist', models.TextField(blank=True, verbose_name='비허용문구')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='시간')),
                ('agent', models.CharField(max_length=30, verbose_name='에이전트')),
                ('cpu', models.CharField(max_length=30, verbose_name='CPU사용량')),
                ('memory', models.CharField(max_length=30, verbose_name='메모리사용량')),
            ],
        ),
    ]
