# Generated by Django 3.0.5 on 2020-04-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='제품명')),
                ('version', models.CharField(max_length=30, verbose_name='버전')),
                ('logpath', models.CharField(max_length=50, verbose_name='로그경로')),
            ],
        ),
        migrations.CreateModel(
            name='Loglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='제품명')),
                ('version', models.CharField(max_length=30, verbose_name='버전')),
                ('whitelist', models.TextField(blank=True, verbose_name='허용문구')),
                ('blacklist', models.TextField(blank=True, verbose_name='비허용문구')),
            ],
        ),
        migrations.CreateModel(
            name='Performagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostype', models.CharField(blank=True, max_length=20, verbose_name='OS')),
                ('process1', models.CharField(blank=True, max_length=20, verbose_name='프로세스1')),
                ('process2', models.CharField(blank=True, max_length=20, verbose_name='프로세스2')),
                ('process3', models.CharField(blank=True, max_length=20, verbose_name='프로세스3')),
                ('process4', models.CharField(blank=True, max_length=20, verbose_name='프로세스4')),
                ('process5', models.CharField(blank=True, max_length=20, verbose_name='프로세스5')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='시간')),
                ('agent', models.CharField(blank=True, max_length=30, verbose_name='에이전트')),
                ('cpu', models.CharField(blank=True, max_length=30, verbose_name='전체CPU사용량')),
                ('memory', models.CharField(blank=True, max_length=30, verbose_name='전체메모리사용량')),
                ('p1cpu', models.CharField(blank=True, max_length=30, verbose_name='p1CPU사용량')),
                ('p1memory', models.CharField(blank=True, max_length=30, verbose_name='p1메모리사용량')),
                ('p2cpu', models.CharField(blank=True, max_length=30, verbose_name='p2CPU사용량')),
                ('p2memory', models.CharField(blank=True, max_length=30, verbose_name='p2메모리사용량')),
                ('p3cpu', models.CharField(blank=True, max_length=30, verbose_name='p3CPU사용량')),
                ('p3memory', models.CharField(blank=True, max_length=30, verbose_name='p3메모리사용량')),
                ('p4cpu', models.CharField(blank=True, max_length=30, verbose_name='p4CPU사용량')),
                ('p4memory', models.CharField(blank=True, max_length=30, verbose_name='p4메모리사용량')),
                ('p5cpu', models.CharField(blank=True, max_length=30, verbose_name='p5CPU사용량')),
                ('p5memory', models.CharField(blank=True, max_length=30, verbose_name='p5메모리사용량')),
            ],
        ),
    ]
