# Generated by Django 2.0.4 on 2018-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='agent',
            field=models.CharField(blank=True, max_length=30, verbose_name='에이전트'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='cpu',
            field=models.CharField(blank=True, max_length=30, verbose_name='CPU사용량'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='메모리사용량'),
        ),
    ]
