# Generated by Django 2.0.4 on 2018-05-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0003_auto_20180509_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performagent',
            name='agentfile',
            field=models.FileField(blank=True, upload_to='agents/', verbose_name='에이전트파일'),
        ),
    ]
