# Generated by Django 2.0.4 on 2018-05-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0004_auto_20180509_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performagent',
            name='agentfile',
            field=models.FileField(blank=True, upload_to='', verbose_name='에이전트파일'),
        ),
    ]
