# Generated by Django 2.0.4 on 2018-05-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0005_auto_20180509_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performagent',
            name='agentfile',
        ),
        migrations.AddField(
            model_name='performagent',
            name='agentpath',
            field=models.CharField(default='a', max_length=50, verbose_name='에이전트경로'),
            preserve_default=False,
        ),
    ]
