# Generated by Django 2.0.4 on 2018-05-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0006_auto_20180509_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='performagent',
            name='ostype',
            field=models.CharField(blank=True, choices=[('Window', '윈도우'), ('Unix/Linux', '유닉스/리눅스')], max_length=10, verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='performagent',
            name='process1',
            field=models.CharField(blank=True, max_length=20, verbose_name='프로세스1'),
        ),
        migrations.AddField(
            model_name='performagent',
            name='process2',
            field=models.CharField(blank=True, max_length=20, verbose_name='프로세스2'),
        ),
        migrations.AddField(
            model_name='performagent',
            name='process3',
            field=models.CharField(blank=True, max_length=20, verbose_name='프로세스3'),
        ),
        migrations.AddField(
            model_name='performagent',
            name='process4',
            field=models.CharField(blank=True, max_length=20, verbose_name='프로세스4'),
        ),
    ]
