# Generated by Django 2.0.4 on 2018-05-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logperform', '0010_performagent_process5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performagent',
            name='ostype',
            field=models.CharField(blank=True, max_length=10, verbose_name='OS'),
        ),
    ]
