# Generated by Django 2.0.4 on 2018-06-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityauto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcolora',
            options={'verbose_name_plural': 'TestColorS'},
        ),
        migrations.AlterModelOptions(
            name='testcolors',
            options={'verbose_name_plural': 'TestColorS'},
        ),
        migrations.AddField(
            model_name='testcolora',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='등록'),
        ),
        migrations.AddField(
            model_name='testcolors',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='등록'),
        ),
        migrations.AlterField(
            model_name='testcolora',
            name='version',
            field=models.CharField(max_length=20, verbose_name='제품버전'),
        ),
        migrations.AlterField(
            model_name='testcolors',
            name='version',
            field=models.CharField(max_length=20, verbose_name='제품버전'),
        ),
    ]
