# Generated by Django 2.0.4 on 2018-06-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityauto', '0003_auto_20180614_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='이름')),
                ('program', models.FileField(upload_to='programs/', verbose_name='프로그램')),
            ],
        ),
    ]
