# Generated by Django 2.0.4 on 2018-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defectloglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='제품')),
                ('word', models.TextField(verbose_name='결함문구')),
            ],
        ),
    ]
