# Generated by Django 2.0.4 on 2018-05-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectloglist',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='등록'),
        ),
    ]
