# Generated by Django 2.0.4 on 2018-05-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0004_auto_20180515_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonitorDefectlog',
            new_name='Monitoringproduct',
        ),
    ]
