# Generated by Django 2.0.4 on 2018-05-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0009_auto_20180517_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringproduct',
            old_name='idNhost',
            new_name='host',
        ),
        migrations.AddField(
            model_name='monitoringproduct',
            name='user',
            field=models.CharField(blank=True, max_length=30, verbose_name='아이디'),
        ),
    ]
