# Generated by Django 2.0.4 on 2018-05-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0014_monitoringproduct_logname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectloglist',
            name='word',
            field=models.TextField(unique=True, verbose_name='결함문구'),
        ),
        migrations.AlterField(
            model_name='monitoringproduct',
            name='logname',
            field=models.CharField(max_length=20, unique=True, verbose_name='파일이름'),
        ),
        migrations.AlterField(
            model_name='monitoringproduct',
            name='logpath',
            field=models.CharField(max_length=100, unique=True, verbose_name='로그경로'),
        ),
    ]
