# Generated by Django 3.0.5 on 2020-04-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defectloglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('SecuMS', 'SecuMS'), ('OmniGuard', 'OmniGuard'), ('FOSSGuard', 'FOSSGuard'), ('Athene', 'Athene')], max_length=30, verbose_name='제품')),
                ('word', models.TextField(unique=True, verbose_name='결함문구')),
                ('marked', models.BooleanField(default=False, verbose_name='등록')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoringproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, unique=True, verbose_name='제품')),
                ('ostype', models.CharField(choices=[('Windows', 'Windows'), ('Unix/Linux', 'Unix/Linux')], max_length=30, unique=True, verbose_name='운영체제')),
                ('logpath', models.CharField(max_length=100, unique=True, verbose_name='로그경로')),
                ('logname', models.CharField(max_length=20, unique=True, verbose_name='파일이름')),
                ('user', models.CharField(blank=True, max_length=30, verbose_name='아이디')),
                ('host', models.CharField(blank=True, max_length=30, verbose_name='호스트')),
                ('pw', models.CharField(blank=True, max_length=30, verbose_name='비밀번호')),
            ],
        ),
    ]
