# Generated by Django 2.0.4 on 2018-05-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0002_defectloglist_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorDefectlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='제품')),
                ('word', models.TextField(verbose_name='결함문구')),
            ],
        ),
    ]
