# Generated by Django 2.0.4 on 2018-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0003_monitordefectlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordefectlog',
            name='word',
            field=models.TextField(unique=True, verbose_name='결함문구'),
        ),
    ]
