# Generated by Django 2.0.4 on 2018-05-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0005_auto_20180517_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringproduct',
            name='idNhost',
            field=models.CharField(blank=True, max_length=30, verbose_name='호스트'),
        ),
        migrations.AddField(
            model_name='monitoringproduct',
            name='pw',
            field=models.CharField(blank=True, max_length=30, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='monitoringproduct',
            name='product',
            field=models.CharField(blank=True, max_length=30, verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='monitoringproduct',
            name='word',
            field=models.TextField(blank=True, verbose_name='결함문구'),
        ),
    ]
