# Generated by Django 2.0.4 on 2018-05-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0008_auto_20180517_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringproduct',
            name='word',
        ),
        migrations.AlterField(
            model_name='defectloglist',
            name='product',
            field=models.CharField(choices=[('SecuMS', 'SecuMS'), ('OmniGuardUnix', 'OmniGuardUnix'), ('OmniGuardWindows', 'OmniGuardWindows'), ('FOSSGuard', 'FOSSGuard'), ('Athene', 'Athene')], max_length=30, verbose_name='제품'),
        ),
    ]
