# Generated by Django 2.0.4 on 2018-05-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0010_auto_20180518_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringproduct',
            name='ostype',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Unix/Linux', 'Unix/Linux')], default='Windows', max_length=30, unique=True, verbose_name='운영체제'),
            preserve_default=False,
        ),
    ]
