# Generated by Django 2.0.4 on 2018-05-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmonitor', '0011_monitoringproduct_ostype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectloglist',
            name='product',
            field=models.CharField(choices=[('SecuMS', 'SecuMS'), ('OmniGuard', 'OmniGuard'), ('FOSSGuard', 'FOSSGuard'), ('Athene', 'Athene')], max_length=30, verbose_name='제품'),
        ),
    ]
