# Generated by Django 3.0.5 on 2020-04-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedPaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('project', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=10)),
                ('master', models.CharField(max_length=10)),
                ('change', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=20)),
            ],
        ),
    ]
