# Generated by Django 3.0.5 on 2020-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redmine_Parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redpaser',
            name='author',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='redpaser',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='redpaser',
            name='change',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='redpaser',
            name='master',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='redpaser',
            name='priority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='redpaser',
            name='project',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='redpaser',
            name='start',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='redpaser',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
