# Generated by Django 2.0.4 on 2018-04-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproc', '0002_totalquality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalquality',
            options={'verbose_name_plural': 'Totalqualities'},
        ),
    ]
