# Generated by Django 2.0.4 on 2018-04-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproc', '0003_auto_20180416_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productquality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30, verbose_name='프로젝트')),
                ('manualtest', models.IntegerField(verbose_name='수동테스트')),
                ('process', models.IntegerField(verbose_name='프로세스')),
                ('faulty', models.IntegerField(verbose_name='결함도')),
                ('date', models.DateField(verbose_name='날짜')),
            ],
            options={
                'verbose_name_plural': 'Productqualities',
            },
        ),
    ]
