# Generated by Django 2.0.2 on 2018-03-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autotest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=30, verbose_name='프로젝트')),
                ('testname', models.CharField(max_length=30, verbose_name='테스트명')),
                ('total', models.IntegerField(verbose_name='전체폴더개수')),
                ('starttime', models.DateTimeField(verbose_name='테스트시간')),
                ('path', models.CharField(max_length=100, verbose_name='경로')),
            ],
        ),
    ]
