# Generated by Django 2.0.3 on 2018-03-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionauto', '0002_auto_20180327_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotest',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='등록'),
        ),
    ]
