# Generated by Django 2.0.3 on 2018-03-27 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('functionauto', '0003_autotest_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testreserve',
            old_name='time',
            new_name='reservetime',
        ),
        migrations.AddField(
            model_name='testreserve',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='테스트시간'),
            preserve_default=False,
        ),
    ]
