# Generated by Django 2.0.3 on 2018-03-27 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('functionauto', '0005_testreserve_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreserve',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작시간'),
        ),
    ]
