# Generated by Django 2.0.4 on 2018-04-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionauto', '0009_auto_20180327_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotest',
            name='path',
            field=models.CharField(blank=True, max_length=100, verbose_name='경로'),
        ),
    ]
