# Generated by Django 2.0.4 on 2018-06-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionauto', '0010_auto_20180416_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotest',
            name='path',
            field=models.CharField(blank=True, choices=[('Linux', '/home/qceo/windowshare/Linux'), ('Solaris', '/home/qceo/windowshare/Solaris_intel'), ('UNIX', '/home/qceo/windowshare/UNIX')], max_length=100, verbose_name='경로'),
        ),
    ]
